//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentWeather.Abstraction.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WeatherCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeatherCodeDescription() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentWeather.Abstraction.Strings.WeatherCodeDescription", typeof(WeatherCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 晴 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_0 {
            get {
                return ResourceManager.GetString("WeatherCode_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大部晴朗 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_1 {
            get {
                return ResourceManager.GetString("WeatherCode_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 局部多云 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_2 {
            get {
                return ResourceManager.GetString("WeatherCode_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阴 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_3 {
            get {
                return ResourceManager.GetString("WeatherCode_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雾 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_45 {
            get {
                return ResourceManager.GetString("WeatherCode_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雾霾 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_48 {
            get {
                return ResourceManager.GetString("WeatherCode_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_51 {
            get {
                return ResourceManager.GetString("WeatherCode_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_53 {
            get {
                return ResourceManager.GetString("WeatherCode_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_55 {
            get {
                return ResourceManager.GetString("WeatherCode_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小冻雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_56 {
            get {
                return ResourceManager.GetString("WeatherCode_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大冻雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_57 {
            get {
                return ResourceManager.GetString("WeatherCode_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_61 {
            get {
                return ResourceManager.GetString("WeatherCode_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_63 {
            get {
                return ResourceManager.GetString("WeatherCode_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_65 {
            get {
                return ResourceManager.GetString("WeatherCode_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小冻雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_66 {
            get {
                return ResourceManager.GetString("WeatherCode_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大冻雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_67 {
            get {
                return ResourceManager.GetString("WeatherCode_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小雪 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_71 {
            get {
                return ResourceManager.GetString("WeatherCode_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中雪 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_73 {
            get {
                return ResourceManager.GetString("WeatherCode_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大雪 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_75 {
            get {
                return ResourceManager.GetString("WeatherCode_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雪粒 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_77 {
            get {
                return ResourceManager.GetString("WeatherCode_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小阵雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_80 {
            get {
                return ResourceManager.GetString("WeatherCode_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中阵雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_81 {
            get {
                return ResourceManager.GetString("WeatherCode_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大阵雨 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_82 {
            get {
                return ResourceManager.GetString("WeatherCode_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小阵雪 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_85 {
            get {
                return ResourceManager.GetString("WeatherCode_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大阵雪 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_86 {
            get {
                return ResourceManager.GetString("WeatherCode_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷暴 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_95 {
            get {
                return ResourceManager.GetString("WeatherCode_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷雨伴小冰雹 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_96 {
            get {
                return ResourceManager.GetString("WeatherCode_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷暴伴大冰雹 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_99 {
            get {
                return ResourceManager.GetString("WeatherCode_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string WeatherCode_Unknown {
            get {
                return ResourceManager.GetString("WeatherCode_Unknown", resourceCulture);
            }
        }
    }
}
